# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Casualidades
email: contato@timeu.com.br
description: "Coisas sobre linux, desenvolvimento, php, shell, coisas da vida, música..."
baseurl: "/blog"
url: "http://timeu.com.br"
twitter_username: timeuz
github_username:  heathz
google_username: 116881261099591656657
facebook_username: timeu.f.oliveira
instagram_username: timeuz

# Build settings
markdown: kramdown

#permalink default
#permalink: /:categories/:year/:month/:day/:title

permalink: /:title
